<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobHistorysedder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $karyawans = [

            [
                'id' => '1',
                'karyawan_id' => '1',
                'nama' => 'General Manager Regional',
                'tgl_jabat' => '2024-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'II',
                'lampiran' => Null,
            ],
            [
                'id' => '2',
                'karyawan_id' => '2',
                'nama' => 'Manager Marketing, Sales & Solution',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '3',
                'karyawan_id' => '3',
                'nama' => 'Senior Officer Sales Support  & Customer Care',
                'tgl_jabat' => '2023-07-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '4',
                'karyawan_id' => '4',
                'nama' => 'Junior Account Manager 1 ',
                'tgl_jabat' => '2021-02-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '5',
                'karyawan_id' => '5',
                'nama' => 'Manager Planning & Delivery',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '6',
                'karyawan_id' => '6',
                'nama' => 'Junior Officer Project Solution & Delivery',
                'tgl_jabat' => '2022-05-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '7',
                'karyawan_id' => '7',
                'nama' => 'Senior Officer Project , Product & Service Delivery',
                'tgl_jabat' => '2023-07-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '8',
                'karyawan_id' => '8',
                'nama' => 'Officer Project Delivery, Adminisration & Controlling',
                'tgl_jabat' => '2021-11-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '9',
                'karyawan_id' => '9',
                'nama' => 'Manager Operation & Maintenance',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '10',
                'karyawan_id' => '10',
                'nama' => 'Junior Officer Operation & Maintenance',
                'tgl_jabat' => '2022-05-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '11',
                'karyawan_id' => '11',
                'nama' => 'Enginner MEP, MSAP & IOT',
                'tgl_jabat' => '2022-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '12',
                'karyawan_id' => '12',
                'nama' => 'Senior Officer Smart Fleet Operation',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '13',
                'karyawan_id' => '13',
                'nama' => 'Manager Business Support & Risk Management',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '14',
                'karyawan_id' => '14',
                'nama' => 'Officer Legal & Procurement',
                'tgl_jabat' => '2024-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '15',
                'karyawan_id' => '15',
                'nama' => 'Senior Officer Shared Service & Performnance Management',
                'tgl_jabat' => '2020-07-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '16',
                'karyawan_id' => '16',
                'nama' => 'Manager Area Kaltimtara',
                'tgl_jabat' => '2023-06-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '17',
                'karyawan_id' => '17',
                'nama' => 'Officer Sales & Operation Support ',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '18',
                'karyawan_id' => '18',
                'nama' => 'Junior Officer Sales & Operation Support ',
                'tgl_jabat' => '2022-05-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '19',
                'karyawan_id' => '19',
                'nama' => 'Engginer Quality Control & Managed Service',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '20',
                'karyawan_id' => '20',
                'nama' => 'Junior Engginer Quality Control & Managed Service',
                'tgl_jabat' => '2020-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '21',
                'karyawan_id' => '21',
                'nama' => 'Officer Project Administration & Controlling',
                'tgl_jabat' => '2021-07-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '22',
                'karyawan_id' => '22',
                'nama' => 'Technician',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'VII',
                'lampiran' => Null,
            ],
            [
                'id' => '23',
                'karyawan_id' => '23',
                'nama' => 'Territory Manager (TARAKAN)',
                'tgl_jabat' => '2023-02-01',
                'lokasi' => 'Regional VI',
                'band' => 'VII',
                'lampiran' => Null,
            ],
            [
                'id' => '24',
                'karyawan_id' => '24',
                'nama' => 'Territory Manager (KALTIM)',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '25',
                'karyawan_id' => '25',
                'nama' => 'Territory Representative Officer (SAMARINDA)',
                'tgl_jabat' => '2018-04-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '26',
                'karyawan_id' => '26',
                'nama' => 'Territory Representative Officer (BONTANG)',
                'tgl_jabat' => '2018-04-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '27',
                'karyawan_id' => '27',
                'nama' => 'Territory Representative Officer (BERAU)',
                'tgl_jabat' => '2018-04-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '28',
                'karyawan_id' => '28',
                'nama' => 'Manager Area KALSELTENG',
                'tgl_jabat' => '2024-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'III',
                'lampiran' => Null,
            ],
            [
                'id' => '29',
                'karyawan_id' => '29',
                'nama' => 'Junior Officer Sales & Operation Support',
                'tgl_jabat' => '2022-08-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '30',
                'karyawan_id' => '30',
                'nama' => 'Engginer Quality Control & Managed Service',
                'tgl_jabat' => Null,
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '31',
                'karyawan_id' => '31',
                'nama' => 'Officer Project Administration & Controlling',
                'tgl_jabat' => '2020-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '32',
                'karyawan_id' => '32',
                'nama' => 'Territory Manager (PALANGKARAYA)',
                'tgl_jabat' => '2023-01-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '33',
                'karyawan_id' => '33',
                'nama' => 'Territory Representative Officer (BANJAR BARU)',
                'tgl_jabat' => '2019-04-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '34',
                'karyawan_id' => '34',
                'nama' => 'Territory Representative Officer (BATU LICIN)',
                'tgl_jabat' => '2021-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '35',
                'karyawan_id' => '35',
                'nama' => 'Territory Representative Officer (TANJUNG)',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '36',
                'karyawan_id' => '36',
                'nama' => 'Territory Representative Officer (SAMPIT)',
                'tgl_jabat' => '2022-05-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '37',
                'karyawan_id' => '37',
                'nama' => 'Manager Area Kalbar',
                'tgl_jabat' => '2021-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'IV',
                'lampiran' => Null,
            ],
            [
                'id' => '38',
                'karyawan_id' => '38',
                'nama' => 'Officer Sales & Operation Support',
                'tgl_jabat' => '2022-09-01',
                'lokasi' => 'Regional VI',
                'band' => 'V',
                'lampiran' => Null,
            ],
            [
                'id' => '39',
                'karyawan_id' => '39',
                'nama' => 'Junior Engginer Quality Control & Managed Service',
                'tgl_jabat' => '2021-03-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],
            [
                'id' => '40',
                'karyawan_id' => '40',
                'nama' => 'Territory Representative Officer (SINTANG)',
                'tgl_jabat' => '2020-02-01',
                'lokasi' => 'Regional VI',
                'band' => 'VI',
                'lampiran' => Null,
            ],

        ];

        DB::table('job_histories')->insert($karyawans);
    }
}
